"""initial schema

Revision ID: 1429fa39bf5e
Revises: 
Create Date: 2026-03-25 19:16:06.417163

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1429fa39bf5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_phone', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('whatsapp_phone_id', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_waba_id', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_token', sa.String(length=500), nullable=True),
    sa.Column('whatsapp_mode', sa.String(length=50), nullable=True),
    sa.Column('whatsapp_app_active', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_twilio_number_sid', sa.String(length=255), nullable=True),
    sa.Column('bot_paused_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assistant_tone', sa.String(length=50), nullable=False),
    sa.Column('assistant_name', sa.String(length=100), nullable=False),
    sa.Column('custom_prompt', sa.String(length=5000), nullable=True),
    sa.Column('google_calendar_token', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('google_watch_channel_id', sa.String(length=255), nullable=True),
    sa.Column('google_watch_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_phone'),
    sa.UniqueConstraint('whatsapp_phone_id')
    )
    op.create_table('availability_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('office_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('appointment_duration_min', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('office_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('primary_reason', sa.String(length=500), nullable=True),
    sa.Column('how_they_found_us', sa.String(length=255), nullable=True),
    sa.Column('internal_notes', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_appointment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_appointment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_appointments', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('office_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('office_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('consultation_reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('post_consultation_notes', sa.String(length=2000), nullable=True),
    sa.Column('instructions', sa.String(length=2000), nullable=True),
    sa.Column('cancelled_by', sa.String(length=50), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('rescheduled_from', sa.UUID(), nullable=True),
    sa.Column('reminder_48h_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_24h_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_2h_sent', sa.Boolean(), nullable=False),
    sa.Column('follow_up_sent', sa.Boolean(), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rescheduled_from'], ['appointments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('office_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('whatsapp_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_intent', sa.String(length=255), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('taken_by_doctor', sa.Boolean(), nullable=False),
    sa.Column('doctor_took_control_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waitlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('office_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('preferred_days', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('preferred_time', sa.String(length=50), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('google_calendar_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('office_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_block', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(length=4000), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('is_doctor_echo', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_message_id', sa.String(length=255), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('google_calendar_events')
    op.drop_table('waitlist')
    op.drop_table('conversations')
    op.drop_table('appointments')
    op.drop_table('time_blocks')
    op.drop_table('patients')
    op.drop_table('availability_schedules')
    op.drop_table('offices')
    # ### end Alembic commands ###
