"""add onboarding_completed to office

Revision ID: 1cc02229472f
Revises: c734dad62a5c
Create Date: 2026-05-11 20:56:56.545228

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc02229472f'
down_revision = 'c734dad62a5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offices', sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offices', 'onboarding_completed')
    # ### end Alembic commands ###
