"""replace reminder flags with day-of reminders

Revision ID: 78abe354d2d8
Revises: a3b7c1d2e4f5
Create Date: 2026-04-12 11:44:11.256000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78abe354d2d8'
down_revision = 'a3b7c1d2e4f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('reminder_morning_sent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('appointments', sa.Column('reminder_4h_sent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('appointments', sa.Column('reminder_1h_sent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('appointments', sa.Column('reminder_15m_sent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('appointments', 'reminder_48h_sent')
    op.drop_column('appointments', 'reminder_2h_sent')
    op.drop_column('appointments', 'reminder_24h_sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('reminder_24h_sent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('reminder_2h_sent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('reminder_48h_sent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('appointments', 'reminder_15m_sent')
    op.drop_column('appointments', 'reminder_1h_sent')
    op.drop_column('appointments', 'reminder_4h_sent')
    op.drop_column('appointments', 'reminder_morning_sent')
    # ### end Alembic commands ###
