"""add owner_phone to offices

Revision ID: c734dad62a5c
Revises: 78abe354d2d8
Create Date: 2026-05-05 20:56:20.873125

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c734dad62a5c'
down_revision = '78abe354d2d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offices', sa.Column('owner_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offices', 'owner_phone')
    # ### end Alembic commands ###
